name: flutter_cat1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.18.1
  cupertino_icons: ^1.0.8 
  google_fonts: ^6.2.1
  sqflite: ^2.1.0+1
  path: ^1.8.0
  http: ^1.1.0
  image_picker: ^1.1.0
  font_awesome_flutter: ^10.6.0 
  shared_preferences: ^2.2.2
 
  
  
  # For generating receipts as PDFs
  pdf: ^3.10.0
  printing: ^5.6.1
  
  # For CSV file handling
  csv: ^5.0.0
  path_provider: ^2.0.11
  file_picker: ^5.0.0
  
  # For JSON encoding/decoding
  json_annotation: ^4.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  

flutter:
  uses-material-design: true
  assets:
    - assets/images/range rear 1.png
    - assets/images/mercedes front 2.jpeg
    - assets/images/mazda cx 5 front.webp
    - assets/images/mazda axela.png
    - assets/images/Lincoln-Stretch-Limousine.png
    - assets/images/mazda demio.jpeg
    - assets/images/land cruizer front 2.webp
    - assets/images/land cruizer front.jpg
    - assets/images/toyota axio front.webp
    - assets/images/audi side.jpeg
